springdoc:
  swagger-ui:
    path: /documentacion.html
  api-docs:
    path: /api-docs

aws:
  dynamodb:
    secret-key: peigo
    access-key: Globant2021
    end-point: http://localhost:8000/
    
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 60000
