package com.peigo.wallet.ms.boilerplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "")
public class User {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "")
    private String id;

    @DynamoDBAttribute(attributeName = "")
    private String name;

    @DynamoDBAttribute(attributeName = "")
    private String email;

    @DynamoDBAttribute(attributeName = "")
    private String age;
}
