package com.peigo.wallet.ms.boilerplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.peigo.wallet.ms.boilerplate.constants.DynamoDBConstant;
import lombok.Data;

@Data
@DynamoDBTable(tableName = DynamoDBConstant.TABLE_NAME)
public class User {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = DynamoDBConstant.ATTRIBUTE_NAME_ID)
    private String id;

    @DynamoDBAttribute(attributeName = DynamoDBConstant.ATTRIBUTE_NAME_NAME)
    private String name;

    @DynamoDBAttribute(attributeName = DynamoDBConstant.ATTRIBUTE_NAME_EMAIL)
    private String email;

    @DynamoDBAttribute(attributeName = DynamoDBConstant.ATTRIBUTE_NAME_AGE)
    private String age;
}
