package com.peigo.wallet.ms.boilerplate.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "users")
public class UserEntity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "age")
    private String age;

    @DynamoDBAttribute(attributeName = "creditCards")
    private List<CreditCardEntity> creditCardEntityList;
}

